version: "3.3"

services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER= expressvpn            # See https://github.com/qdm12/gluetun/wiki
      - VPN_TYPE= openvpn
      - OPENVPN_USER= DTO41
      - OPENVPN_PASSWORD= dto410
      - SERVER_COUNTRIES= Turkey                # See https://github.com/qdm12/gluetun/wiki 
    ports:
      - "88:88"                          # Add ports that you want to expose
      - "8888:8888"
    restart: always
  app:
    build: .
    network_mode: "service:gluetun"
    depends_on:
      gluetun:
        condition: service_started 
    command: bash start.sh
    restart: always
    
